version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directories:
      - "/benchmark"
      - "/examples"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "JET"
      - dependency-name: "IRTools"
