name: performance tracking

on:
  pull_request:

permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1"
      - name: install dependencies
        run: |
          julia --startup-file=no --project="$RUNNER_TEMP/benchmark-runner" -e '
          using Pkg
          Pkg.add(PackageSpec(; name="PkgBenchmark", version=v"0.2.15"))
          '

      # run the benchmark suite and record the result as markdown
      - name: run benchmarks
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          JULIA_LOAD_PATH: "@:${{ github.workspace }}/benchmark:@stdlib"
        run: |
          julia --startup-file=no --project="$RUNNER_TEMP/benchmark-runner" -e '
          using PkgBenchmark

          let pkgdir = abspath(pwd())
              mktempdir() do workspace
                  script = joinpath(workspace, "benchmarks.jl")
                  open(script, "w") do io
                      project = joinpath(pkgdir, "benchmark")
                      benchmark = joinpath(project, "benchmarks.jl")
                      println(io, "using Pkg")
                      println(io, "Pkg.activate(", repr(project), ")")
                      println(io, "Pkg.instantiate()")
                      println(io, "include(", repr(benchmark), ")")
                  end

                  judgement = PkgBenchmark.judge(
                      pkgdir,
                      ENV["BASE_SHA"];
                      script,
                  )
                  open("benchmark-result.artifact", "w") do io
                      println(io, "<details>")
                      println(io, "<summary>JET Benchmark Result</summary>")
                      println(io)
                      println(io, "# Judge result")
                      PkgBenchmark.export_markdown(io, judgement)
                      println(io, "\n---\n")
                      println(io, "# Target result")
                      PkgBenchmark.export_markdown(
                          io,
                          PkgBenchmark.target_result(judgement),
                      )
                      println(io, "\n---\n")
                      println(io, "# Baseline result")
                      PkgBenchmark.export_markdown(
                          io,
                          PkgBenchmark.baseline_result(judgement),
                      )
                      println(io)
                      println(io)
                      println(io, "</details>")
                  end
              end
          end
          '

      # record the pull request number
      - name: record pull request number
        run: echo ${{ github.event.pull_request.number }} > ./pull-request-number.artifact

      # save as artifacts (performance tracking (comment) workflow will use it)
      - uses: actions/upload-artifact@v7
        with:
          name: performance-tracking
          path: ./*.artifact
