name: CI – Empty loading test on nightly

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  empty-loading-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: 'nightly'
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
